In [2]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.image as mpimg
import os
import random
import pandas as pd
from sklearn.metrics import accuracy_score, confusion_matrix
from sklearn.ensemble import RandomForestClassifier
from sklearn import svm, tree
import xgboost
from sklearn.feature_extraction.text import TfidfVectorizer
from xgboost import plot_tree
import seaborn as sns
import xlwt
from xlwt import Workbook
from sklearn.preprocessing import OneHotEncoder
from sklearn import preprocessing
from sklearn import datasets, linear_model, metrics
from sklearn.metrics import accuracy_score, confusion_matrix
from sklearn.ensemble import RandomForestClassifier
from sklearn import svm, tree
import xgboost
import csv
from scipy import sparse
from sklearn.naive_bayes import BernoulliNB
from sklearn.multioutput import MultiOutputClassifier
from sklearn.neighbors import KNeighborsClassifier
from numpy import count_nonzero

In [3]:
import os
import cv2
import numpy as np
import matplotlib.pyplot as plt
import random
import tensorflow as tf
from tensorflow.keras.datasets import cifar10
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout, Activation, Flatten
from tensorflow.keras.layers import Conv2D, MaxPooling2D

In [4]:
df = pd.read_csv("dataset/train.csv")

In [5]:
len(df.columns)

785

In [6]:
label = df.values

In [7]:
label = label[:,0:1]

In [8]:
train  = df

In [9]:
train = train.drop("label",axis=1)

In [10]:
train = train.values

In [11]:
def check_null(daf,col):
    count = 0
    x = daf[col].isnull()
    arr = x.values.tolist()
    for i in arr:
        if(i):
            count+=1
    if(count>=0):
        print("The length of the {} is {} and null values are {} and datatype is {}".format(col,str(len(arr)),str(count),daf[col].dtypes ))


In [12]:
X = train[:,0:len(train)]

In [13]:
y = label

In [14]:
print(X)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [15]:
print(y)

[[1]
 [0]
 [1]
 ...
 [7]
 [6]
 [9]]


In [16]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=101)

In [17]:
print(X_train.shape,X_test.shape,y_train.shape,y_test.shape)

(29400, 784) (12600, 784) (29400, 1) (12600, 1)


In [18]:
model = xgboost.XGBClassifier()

In [19]:
model.fit(X_train,y_train)

C:\Users\amishra3\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\preprocessing\label.py:219: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\amishra3\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\preprocessing\label.py:252: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=1, gamma=0,
              learning_rate=0.1, max_delta_step=0, max_depth=3,
              min_child_weight=1, missing=None, n_estimators=100, n_jobs=1,
              nthread=None, objective='multi:softprob', random_state=0,
              reg_alpha=0, reg_lambda=1, scale_pos_weight=1, seed=None,
              silent=None, subsample=1, verbosity=1)

In [20]:
res = model.predict(X_test)

In [21]:
ans = accuracy_score(res,y_test)

In [22]:
print(ans*100)

93.53968253968254


In [75]:
neural_model = Sequential([Dense(128,activation="relu",input_shape=X_test.shape[1:]),
                           Dense(64,activation="relu"),
                           Dropout(0.5),
                           Dense(32,activation="relu"),
                           Dense(10,activation="softmax")
                            ])


In [76]:
neural_model.compile(optimizer="adam",loss="sparse_categorical_crossentropy",metrics=["accuracy"])

In [77]:
hist = neural_model.fit(X_train,y_train,batch_size=32,epochs=20,validation_data=(X_test,y_test))

Train on 29400 samples, validate on 12600 samples
Epoch 1/20
29400/29400 [==============================] - 3s 92us/sample - loss: 3.1916 - acc: 0.4286 - val_loss: 0.8428 - val_acc: 0.7356
Epoch 2/20
29400/29400 [==============================] - 2s 85us/sample - loss: 1.2575 - acc: 0.5766 - val_loss: 0.7129 - val_acc: 0.8028
Epoch 3/20
29400/29400 [==============================] - 3s 88us/sample - loss: 1.1131 - acc: 0.6293 - val_loss: 0.5690 - val_acc: 0.8639
Epoch 4/20
29400/29400 [==============================] - 3s 91us/sample - loss: 0.9566 - acc: 0.6854 - val_loss: 0.4927 - val_acc: 0.8784
Epoch 5/20
29400/29400 [==============================] - 3s 85us/sample - loss: 0.8542 - acc: 0.7276 - val_loss: 0.4474 - val_acc: 0.8935
Epoch 6/20
29400/29400 [==============================] - 3s 103us/sample - loss: 0.7738 - acc: 0.7677 - val_loss: 0.4438 - val_acc: 0.8997
Epoch 7/20
29400/29400 [==============================] - 3s 90us/sample - loss: 0.6966 - acc: 0.7882 - val_loss: 0

In [41]:
test = pd.read_csv("dataset/test.csv")

In [42]:
test.head()

pixel0  pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  pixel8  \
0       0       0       0       0       0       0       0       0       0   
1       0       0       0       0       0       0       0       0       0   
2       0       0       0       0       0       0       0       0       0   
3       0       0       0       0       0       0       0       0       0   
4       0       0       0       0       0       0       0       0       0   

   pixel9  ...  pixel774  pixel775  pixel776  pixel777  pixel778  pixel779  \
0       0  ...         0         0         0         0         0         0   
1       0  ...         0         0         0         0         0         0   
2       0  ...         0         0         0         0         0         0   
3       0  ...         0         0         0         0         0         0   
4       0  ...         0         0         0         0         0         0   

   pixel780  pixel781  pixel782  pixel783  
0         0         0         0         0  
1         0         0         0         0  
2         0         0         0         0  
3         0         0         0         0  
4         0         0         0         0  

[5 rows x 784 columns]

In [43]:
test = test.values

In [44]:
test = test[:,0:len(test)]

In [46]:
print(test.shape)

(28000, 784)


In [47]:
ans1 = model.predict(test)

In [78]:
ans2 = neural_model.predict(test)

In [80]:
print(type(ans2))

<class 'numpy.ndarray'>


In [84]:
ans2 = ans2.tolist()

In [85]:
print(type(ans2))

<class 'list'>


In [90]:
print(ans2[0])

[1.161048883134686e-20, 2.1402928040981095e-11, 1.0, 3.118978599697675e-13, 1.5186243903907001e-22, 2.659384710891984e-25, 2.86671043215357e-23, 3.827887340435154e-09, 1.0319292206894261e-21, 3.0873920615786135e-23]
